// Auto-generated by Supabase CLI — do not edit manually
// Regenerate with: npm run gen:types
//
// Placeholder until migrations are applied and types are generated.
// Run: SUPABASE_PROJECT_REF=your-ref npm run gen:types

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      households: {
        Row: { id: string; name: string; created_at: string }
        Insert: { id?: string; name?: string; created_at?: string }
        Update: { id?: string; name?: string; created_at?: string }
      }
      profiles: {
        Row: {
          id: string
          display_name: string | null
          household_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          display_name?: string | null
          household_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          display_name?: string | null
          household_id?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      categories: {
        Row: {
          id: string
          household_id: string
          name: string
          sort_order: number
          is_default: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          household_id: string
          name: string
          sort_order?: number
          is_default?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          household_id?: string
          name?: string
          sort_order?: number
          is_default?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      recipes: {
        Row: {
          id: string
          household_id: string
          title: string
          servings: number | null
          prep_time: number | null
          cook_time: number | null
          source_url: string | null
          directions: string | null
          image_url: string | null
          notes: string | null
          ai_parsed: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          household_id: string
          title: string
          servings?: number | null
          prep_time?: number | null
          cook_time?: number | null
          source_url?: string | null
          directions?: string | null
          image_url?: string | null
          notes?: string | null
          ai_parsed?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          household_id?: string
          title?: string
          servings?: number | null
          prep_time?: number | null
          cook_time?: number | null
          source_url?: string | null
          directions?: string | null
          image_url?: string | null
          notes?: string | null
          ai_parsed?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      recipe_ingredients: {
        Row: {
          id: string
          recipe_id: string
          text: string
          quantity: string | null
          unit: string | null
          coles_product: string | null
          sort_order: number
          created_at: string
        }
        Insert: {
          id?: string
          recipe_id: string
          text: string
          quantity?: string | null
          unit?: string | null
          coles_product?: string | null
          sort_order?: number
          created_at?: string
        }
        Update: {
          id?: string
          recipe_id?: string
          text?: string
          quantity?: string | null
          unit?: string | null
          coles_product?: string | null
          sort_order?: number
          created_at?: string
        }
      }
      pantry_items: {
        Row: {
          id: string
          household_id: string
          name: string
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          household_id: string
          name: string
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          household_id?: string
          name?: string
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      longlist_items: {
        Row: {
          id: string
          household_id: string
          name: string
          category_id: string | null
          default_qty: number
          unit: string | null
          is_staple: boolean
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          household_id: string
          name: string
          category_id?: string | null
          default_qty?: number
          unit?: string | null
          is_staple?: boolean
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          household_id?: string
          name?: string
          category_id?: string | null
          default_qty?: number
          unit?: string | null
          is_staple?: boolean
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      coles_preferences: {
        Row: {
          id: string
          household_id: string
          product_name: string
          pack_size: string | null
          brand: string | null
          last_price: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          household_id: string
          product_name: string
          pack_size?: string | null
          brand?: string | null
          last_price?: number | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          household_id?: string
          product_name?: string
          pack_size?: string | null
          brand?: string | null
          last_price?: number | null
          created_at?: string
          updated_at?: string
        }
      }
      weekly_sessions: {
        Row: {
          id: string
          household_id: string
          session_date: string
          status: 'draft' | 'planning' | 'picking' | 'review' | 'finalised' | 'dispatched'
          meal_ingredients: Json | null
          confirmed_other_items: Json | null
          dropped_duplicates: Json | null
          pantry_exclusions: Json | null
          final_list: Json | null
          coles_dispatched: boolean
          reminders_exported: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          household_id: string
          session_date?: string
          status?: 'draft' | 'planning' | 'picking' | 'review' | 'finalised' | 'dispatched'
          meal_ingredients?: Json | null
          confirmed_other_items?: Json | null
          dropped_duplicates?: Json | null
          pantry_exclusions?: Json | null
          final_list?: Json | null
          coles_dispatched?: boolean
          reminders_exported?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          household_id?: string
          session_date?: string
          status?: 'draft' | 'planning' | 'picking' | 'review' | 'finalised' | 'dispatched'
          meal_ingredients?: Json | null
          confirmed_other_items?: Json | null
          dropped_duplicates?: Json | null
          pantry_exclusions?: Json | null
          final_list?: Json | null
          coles_dispatched?: boolean
          reminders_exported?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      weekly_meals: {
        Row: { id: string; session_id: string; recipe_id: string; notes: string | null; created_at: string }
        Insert: { id?: string; session_id: string; recipe_id: string; notes?: string | null; created_at?: string }
        Update: { id?: string; session_id?: string; recipe_id?: string; notes?: string | null; created_at?: string }
      }
      automation_logs: {
        Row: { id: string; session_id: string; message: string; log_type: string; created_at: string }
        Insert: { id?: string; session_id: string; message: string; log_type?: string; created_at?: string }
        Update: { id?: string; session_id?: string; message?: string; log_type?: string; created_at?: string }
      }
    }
    Functions: {
      current_household_id: { Args: Record<string, never>; Returns: string }
      advance_session: { Args: { p_session_id: string }; Returns: string }
    }
    Enums: {
      session_status: 'draft' | 'planning' | 'picking' | 'review' | 'finalised' | 'dispatched'
    }
  }
}
